added_comment_and_review_models
ViktorAllayarov/api_yamdb pull request #1
Opened 2023-02-21 12:53 UTC by ilyaryk

2023-02-21 13:09 UTC, ViktorAllayarov commented on api_yamdb/reviews/models.py
> +    user = models.ForeignKey(User,
тут субъективно конечно, но мне кажется user лучше поменять на author

2023-02-21 13:11 UTC, ilyaryk commented on api_yamdb/reviews/models.py
> +    user = models.ForeignKey(User,
Я тоже так думаю, но в тз к ней обращались как к user, поэтому так и выбрал.

2023-02-21 13:15 UTC, ViktorAllayarov commented on api_yamdb/reviews/models.py
> +    title = models.ForeignKey(Title,
Ты запускал код? он работает? тут используется Title, но Title не импортирован, предлагаю Title создать в файле models.py прям в корне проекта, раз уж это проект произведений. и оттуда импортировать

2023-02-21 13:18 UTC, ViktorAllayarov commented on api_yamdb/reviews/models.py
> +        unique_together = ('author', 'review',)
тут прикольно, типа чтобы не было двух одинаковых комментариев от одного автора?

2023-02-21 13:26 UTC, ViktorAllayarov requested changes
Написал комментарии, посмотри пожалуйста

2023-02-21 13:42 UTC, ViktorAllayarov commented on api_yamdb/reviews/models.py
> +    user = models.ForeignKey(User,
в redoc вот такой ответ при получении списка отзывов должен быть:
{
  "count": 0,
  "next": "string",
  "previous": "string",
  "results": [
    {
    "id": 0,
    "text": "string",
    "author": "string",
    "score": 1,
    "pub_date": "2019-08-24T14:15:22Z"
    }
    ]
}
всетаки думаю author
И кстати вместо поля created - pub_date, в commets тоже pub_date

2023-02-22 11:27 UTC, ilyaryk commented on api_yamdb/reviews/models.py
> +    title = models.ForeignKey(Title,
Title все равно в том же файле находится

2023-02-22 14:54 UTC, ViktorAllayarov approved these changes
Принято с одной небольшой правкой

2023-02-22 14:55 UTC, MarbasWP approved these changes

2023-02-22 14:56 UTC, merged